name: 'Extrair Versões'
description: 'Extrai as Versões de um Projeto Maven'
outputs:
  releaseVersion:
    value: ${{ steps.versions.outputs.releaseVersion }}
  nextMinorVersion: 
    value: ${{ steps.versions.outputs.nextMinorVersion }}
  nextPatchVersion:
    value: ${{ steps.versions.outputs.nextIncrementalVersion }}
  xVersion:
    value: ${{ steps.versions.outputs.xVersion }}
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash