name: Criar release do GitHub

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  push:
    tags:
      - 'v*.0'

jobs:
  create-patch-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG: ${{ inputs.tag && inputs.tag || github.ref }}
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: version
        with:
          value: ${{ env.TAG }}
          index_of_str: "v"
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
      - run: mkdir artifacts
      - name: Baixar Artefatos
        run: find -name 'pom.xml' -exec mvn dependency:get dependency:copy -Dartifact=\${project.groupId}:\${project.artifactId}:${{ steps.version.outputs.substring }}:\${project.packaging} -DoutputDirectory=$PWD/artifacts \;
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Criar Release
        id: create_release
        run: gh release create $TAG artifacts/*.jar artifacts/*.war artifacts/*.ear artifacts/*.zip --title=$TAG --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
