name: Criar branch de correção

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  push:
    tags:
      - 'v**.0'

env:
  TAG: ${{ inputs.tag && inputs.tag || github.ref }}

jobs:
  create-patch-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}
      - uses: actions/checkout@v3
        with:
          ref: master
          path: .master
      - id: extract-version
        uses: ./.master/.github/actions/extract-version
      - name: Configura usuário do Git
        run: |
          git config user.name ${{ vars.COMMIT_USER_NAME }}
          git config user.email ${{ vars.COMMIT_USER_EMAIL }}
      - name: Criando branch de correção
        run: |
          git branch release/v$X_VERSION
      - name: Atualizando versão
        env:      
          RELEASE_VERSION: ${{ steps.extract-version.outputs.releaseVersion }}
          NEXT_PATCH_VERSION: ${{ steps.extract-version.outputs.nextPatchVersion }}
          X_VERSION: ${{ steps.extract-version.outputs.xVersion }}
        run: |
          mvn -B release:update-versions -DdevelopmentVersion=$NEXT_PATCH_VERSION-SNAPSHOT
          git add */pom.xml
          git commit -m "release: iniciando próxima versão (v$NEXT_PATCH_VERSION-SNAPSHOT)"
      - name: Removendo pasta .github
        run: |
          rm -rf .github
          cp -r .master/.github .github
          git add .github/*
          git commit -m "removendo .github a partir da master"
      - name: Enviando modificações
        run: git push origin release/v$X_VERSION
