name: Criar release do GitHub

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        type: string
  push:
    tags:
      - 'v*.0'

jobs:
  extract-version:
    uses: ./.github/workflows/extract-version.yml
  create-patch-branch:
    runs-on: ubuntu-latest
    needs: extract-version
    permissions:
      contents: write
    env:
      RELEASE_VERSION: ${{ github.event_name != 'workflow_dispatch' && needs.extract-version.outputs.releaseVersion || inputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
      - run: mkdir artifacts
      - name: Baixar Artefatos
        run: mvn dependency:get dependency:copy -Dartifact=\${project.groupId}:\${project.artifactId}:$RELEASE_VERSION -DoutputDirectory=artifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Criar Release
        id: create_release
        run: gh release create v$RELEASE_VERSION artifacts/*.jar --title=v$RELEASE_VERSION --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
