name: Implantar versão SNAPSHOT

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'release/**'

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Obtendo o código da aplicação
        uses: actions/checkout@v3
      - name: Configurando JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
      - name: Implantando
        run: mvn -B deploy -DaltDeploymentRepository=github:https://maven.pkg.github.com/${{github.repository}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
