name: Implantar SNAPSHOT

on:
  workflow_dispatch:
  push: 
    branches: 
      - 'master'
      - 'release/**'

jobs:
  make-cache:
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref }}
    steps:
      - name: Obtendo o código da aplicação
        uses: actions/checkout@v3
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
      - name: Obtendo dependências 
        run: mvn dependency:go-offline
        
  deploy-snapshot:
    runs-on: ubuntu-latest
    env:
      GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}      
    permissions:
      packages: write
    steps:
      - name: Obtendo o código da aplicação
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch && github.event.workflow_run.head_branch || github.ref_name }}
      - name: Configurando JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
      - name: Implantando
        run: mvn -B deploy -Prelease -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
