name: Implantar

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  push:
    tags:
      - 'v**.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ inputs.tag && inputs.tag || github.ref }}
    permissions:
      packages: write
    
      
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.TAG }}
    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'
    - name: Criando arquivo Release
      run: echo scm.tag=$TAG >> release.properties
    - name: Implantando
      run: mvn -B release:perform -DconnectionUrl=scm:git:file:///\${project.basedir}
      env:
        GITHUB_TOKEN: ${{ github.token }} 
