name: Implantar SNAPSHOT

on:
  workflow_dispatch:
  push: 
    branches: 
      - 'master'
      - 'release/**'

jobs:
  deploy-snapshot:  
    runs-on: ubuntu-latest
    env:
      GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}      
    permissions:
      packages: write
    steps:
      - name: Aguardando Teste
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: testing
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Obtendo o código da aplicação
        uses: actions/checkout@v3
      - name: Configurando JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
      - name: Implantando
        run: mvn -B deploy -Prelease -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
