name: Publicar

on:
  workflow_dispatch

env:
  COMMIT_USER_NAME: github-actions
  COMMIT_USER_EMAIL: noreply@github.com

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.versions.outputs.releaseVersion }}
      nextMinorVersion: ${{ steps.versions.outputs.nextMinorVersion }}
      nextPatchVersion: ${{ steps.versions.outputs.nextIncrementalVersion }}
      xVersion: ${{ steps.versions.outputs.xVersion }}
    steps:
      - uses: actions/checkout@v3
      - name: Preparar variáveis
        id: versions
        run: |
          majorNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout)
          minorNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.minorVersion -q -DforceStdout)
          incrementalNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.incrementalVersion -q -DforceStdout)
          nextMinorNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.nextMinorVersion -q -DforceStdout)
          nextIncrementalNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.nextIncrementalVersion -q -DforceStdout)
          xVersion=$majorNumber.$minorNumber.x
          releaseVersion=$majorNumber.$minorNumber.$incrementalNumber
          nextMinorVersion=$majorNumber.$nextMinorNumber.0
          nextIncrementalVersion=$majorNumber.$minorNumber.$nextIncrementalNumber
          echo "releaseVersion=$releaseVersion" >> "$GITHUB_OUTPUT"
          echo "xVersion=$xVersion" >> "$GITHUB_OUTPUT"
          echo "nextIncrementalVersion=$nextIncrementalVersion" >> "$GITHUB_OUTPUT"
          echo "nextMinorVersion=$nextMinorVersion" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: prepare-variables
    env:
      RELEASE_VERSION: ${{ needs.prepare-variables.outputs.releaseVersion }}
      NEXT_MINOR_VERSION: ${{ needs.prepare-variables.outputs.nextMinorVersion }}
      NEXT_PATCH_VERSION: ${{ needs.prepare-variables.outputs.nextPatchVersion }}
      X_VERSION: ${{ needs.prepare-variables.outputs.xVersion }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
      - name: Configura usuário do Git
        run: |
          git config user.name $COMMIT_USER_NAME
          git config user.email $COMMIT_USER_EMAIL
      - name: Lançar versão e iniciar proxíma versão menor
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        run: |
          mvn -B release:prepare -DdevelopmentVersion=$NEXT_MINOR_VERSION-SNAPSHOT
          git push origin v$RELEASE_VERSION
          git push
          mvn -B release:perform
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Lançar versão e iniciar proxíma versão de correção
        if: ${{ startsWith(github.ref_name, 'release/' )}}
        run: |
          mvn -B release:prepare -DdevelopmentVersion=$NEXT_PATCH_VERSION-SNAPSHOT
          git push origin v$RELEASE_VERSION
          git push
          mvn -B release:perform
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: mkdir artifacts
      - name: Construir Artefatos
        run: mvn -B package --file pom.xml dependency:copy -Dartifact=\${project.groupId}:\${project.artifactId}:$RELEASE_VERSION -DoutputDirectory=artifacts
      - name: Criar Release
        id: create_release
        run: gh release create v$RELEASE_VERSION artifacts/*.jar --title=v$RELEASE_VERSION --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
  create-hotfix-branch:
    runs-on: ubuntu-latest
    needs: [prepare-variables, build]
    permissions:
      contents: write
    env:
      RELEASE_VERSION: ${{ needs.prepare-variables.outputs.releaseVersion }}
      NEXT_PATCH_VERSION: ${{ needs.prepare-variables.outputs.nextPatchVersion }}
      X_VERSION: ${{ needs.prepare-variables.outputs.xVersion }}
    steps:
      - uses: actions/checkout@v3
      - name: Configura usuário do Git
        run: |
          git config user.name $COMMIT_USER_NAME
          git config user.email $COMMIT_USER_EMAIL
      - name: Criando branch de correção
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        run: |
          git fetch
          git checkout tags/v$RELEASE_VERSION -b release/v$X_VERSION
          mvn -B release:update-versions -DdevelopmentVersion=$NEXT_PATCH_VERSION-SNAPSHOT
          git add pom.xml
          git commit -m "release: iniciando próxima versão (v$NEXT_PATCH_VERSION-SNAPSHOT)"
          git push origin release/v$X_VERSION
