name: Publicar

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'

      - name: Checkout Actions da master
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.repository.default_branch}}
          path: .master
      - id: extract-version
        uses: ./.master/.github/actions/extract-version

      - name: Configura usuário do Git
        run: |
          git config user.name ${{ vars.COMMIT_USER_NAME }}
          git config user.email ${{ vars.COMMIT_USER_EMAIL }}

      - name: Lançar versão e iniciar proxíma versão menor
        env:
          NEXT_MINOR_VERSION: ${{ steps.extract-version.outputs.nextMinorVersion }}
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        run: |
          mvn -B release:prepare -DdevelopmentVersion=$NEXT_MINOR_VERSION-SNAPSHOT

      - name: Lançar versão e iniciar proxíma versão de correção
        env:
          NEXT_PATCH_VERSION: ${{ steps.extract-version.outputs.nextPatchVersion }}
        if: ${{ startsWith(github.ref_name, 'release/' )}}
        run: |
          mvn -B release:prepare -DdevelopmentVersion=$NEXT_PATCH_VERSION-SNAPSHOT

      - name: Push
        env:
          RELEASE_VERSION: ${{ steps.extract-version.outputs.releaseVersion }}
        run: |
          git push
          git push origin v$RELEASE_VERSION
    outputs:
      tag: v${{ steps.extract-version.outputs.releaseVersion }}
    
  create-patch-branch:
    uses: ./.github/workflows/create-patch-branch.yml
    needs: [release]
    with:
      tag: ${{ needs.release.outputs.tag }}
  create-github-release:
    permissions: 
      contents: write
    uses: ./.github/workflows/create-github-release.yml
    needs: [release]
    with:
      tag: ${{ needs.release.outputs.tag }}
  deploy:
    permissions: 
      packages: write
    uses: ./.github/workflows/deploy.yml
    needs: [release]
    with:
      tag: ${{ needs.release.outputs.tag }}
