name: Testar

on:
  push:
   branches: 
    - '**'
   tags-ignore: 
    - '**'

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    env:
      GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
    steps:
      - name: Obtendo o código da aplicação
        uses: actions/checkout@v3
      - id: setup
        name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
      - name: Obtendo dependências 
        if: steps.setup.outputs.cache-hit != 'true'
        run: mvn dependency:go-offline
      - name: Testando
        run: mvn -B verify
