name: versions
run-name: versions

on:
  workflow_call:
    outputs:
      releaseVersion:
        value: ${{ jobs.prepare-variables.outputs.releaseVersion }}
      nextMinorVersion:
        value: ${{ jobs.prepare-variables.outputs.nextMinorVersion }}
      nextPatchVersion:
        value: ${{ jobs.prepare-variables.outputs.nextIncrementalVersion }}
      xVersion:
        value: ${{ jobs.prepare-variables.outputs.xVersion }}

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.versions.outputs.releaseVersion }}
      nextMinorVersion: ${{ steps.versions.outputs.nextMinorVersion }}
      nextPatchVersion: ${{ steps.versions.outputs.nextIncrementalVersion }}
      xVersion: ${{ steps.versions.outputs.xVersion }}
    steps:
      - uses: actions/checkout@v3
      - name: Preparar variáveis
        id: versions
        run: |
          majorNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout)
          minorNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.minorVersion -q -DforceStdout)
          incrementalNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.incrementalVersion -q -DforceStdout)
          nextMinorNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.nextMinorVersion -q -DforceStdout)
          nextIncrementalNumber=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.nextIncrementalVersion -q -DforceStdout)
          xVersion=$majorNumber.$minorNumber.x
          releaseVersion=$majorNumber.$minorNumber.$incrementalNumber
          nextMinorVersion=$majorNumber.$nextMinorNumber.0
          nextIncrementalVersion=$majorNumber.$minorNumber.$nextIncrementalNumber
          echo "releaseVersion=$releaseVersion" >> "$GITHUB_OUTPUT"
          echo "xVersion=$xVersion" >> "$GITHUB_OUTPUT"
          echo "nextIncrementalVersion=$nextIncrementalVersion" >> "$GITHUB_OUTPUT"
          echo "nextMinorVersion=$nextMinorVersion" >> "$GITHUB_OUTPUT"